import React from 'react';
import { ScrollView, Text } from 'react-native';
import styles from './styles';

const PrivacyPolicyView = props => {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.mText}>
      Last updated: May 01, 2020
      </Text>
      <Text style={styles.mText}>
      This Privacy Policy describes Our policies and procedures on the collection,
use and disclosure of Your information when You use the Service and tells You
about Your privacy rights and how the law protects You.
      </Text>
      <Text style={styles.mText}>
      We use Your Personal data to provide and improve the Service. By using the
Service, You agree to the collection and use of information in accordance with
this Privacy Policy.
      </Text>
      <Text style={styles.mText}>
      Interpretation and Definitions 
      </Text>
      <Text style={styles.mText}>
      Interpretation  
      </Text>
      <Text style={styles.mText}>
      The words of which the initial letter is capitalized have meanings defined
under the following conditions.

      </Text>
      <Text style={styles.mText}>
      The following definitions shall have the same meaning regardless of whether
they appear in singular or in plural.
      </Text>
      <Text style={styles.mText}>
      Definitions  
      </Text>
      <Text style={styles.mText}>
      For the purposes of this Privacy Policy:
      </Text>
      <Text style={styles.text}>
      You means the individual accessing or using the Service, or the company,
    or other legal entity on behalf of which such individual is accessing or
    using the Service, as applicable.
      </Text>
      <Text style={styles.text}>
      Company (referred to as either "the Company", "We", "Us" or "Our" in this
    Agreement) refers to Paradyse Inc., 105 Greene Street, Apt. 1003.
      </Text>
      <Text style={styles.text}>
      Application means the software program provided by the Company downloaded
    by You on any electronic device, named Paradyse
      </Text>
      <Text style={styles.text}>
      Affiliate means an entity that controls, is controlled by or is under
    common control with a party, where "control" means ownership of 50% or
    more of the shares, equity interest or other securities entitled to vote
    for election of directors or other managing authority.
      </Text>
      <Text style={styles.text}>
      LAccount means a unique account created for You to access our Service or
    parts of our Service.
      </Text>
      <Text style={styles.text}>
      Website refers to Paradyse, accessible from https://paradyse.app
      </Text>
      <Text style={styles.text}>
      Service refers to the Application or the Website or both.
      </Text>
      <Text style={styles.text}>
      Country refers to: New Jersey, United States
      </Text>
      <Text style={styles.text}>
      Service Provider means any natural or legal person who processes the data
    on behalf of the Company. It refers to third-party companies or
    individuals employed by the Company to facilitate the Service, to provide
    the Service on behalf of the Company, to perform services related to the
    Service or to assist the Company in analyzing how the Service is used.
      </Text>
      <Text style={styles.text}>
      Third-party Social Media Service refers to any website or any social
    network website through which a User can log in or create an account to
    use the Service.
      </Text>
      <Text style={styles.text}>
      Personal Data is any information that relates to an identified or
    identifiable individual.
      </Text>
      <Text style={styles.text}>
      For the purposes of the CCPA, Personal Data means any information that
    identifies, relates to, describes or is capable of being associated with,
    or could reasonably be linked, directly or indirectly, with You.
      </Text>
      <Text style={styles.text}>
      Cookies are small files that are placed on Your computer, mobile device or
    any other device by a website, containing the details of Your browsing
    history on that website among its many uses.
      </Text>
      <Text style={styles.text}>
      Device means any device that can access the Service such as a computer, a
    cellphone or a digital tablet.
      </Text>
      <Text style={styles.text}>
      Usage Data refers to data collected automatically, either generated by the
    use of the Service or from the Service infrastructure itself (for example,
    the duration of a page visit).
      </Text>
      <Text style={styles.text}>
      Do Not Track (DNT) is a concept that has been promoted by US regulatory
    authorities, in particular the U.S. Federal Trade Commission (FTC), for
    the Internet industry to develop and implement a mechanism for allowing
    internet users to control the tracking of their online activities across
    websites.
      </Text>
      <Text style={styles.text}>
      Business, for the purpose of the CCPA (California Consumer Privacy Act),
    refers to the Company as the legal entity that collects Consumers'
    personal information and determines the purposes and means of the
    processing of Consumers' personal information, or on behalf of which such
    information is collected and that alone, or jointly with others,
    determines the purposes and means of the processing of consumers' personal
    information, that does business in the State of California.
      </Text>
      <Text style={styles.text}>
      Consumer, for the purpose of the CCPA (California Consumer Privacy Act),
    means a natural person who is a California resident. A resident, as
    defined in the law, includes (1) every individual who is in the USA for
    other than a temporary or transitory purpose, and (2) every individual who
    is domiciled in the USA who is outside the USA for a temporary or
    transitory purpose.
      </Text>
      <Text style={styles.text}>
      Sale, for the purpose of the CCPA (California Consumer Privacy Act), means
    selling, renting, releasing, disclosing, disseminating, making available,
    transferring, or otherwise communicating orally, in writing, or by
    electronic or other means, a Consumer's Personal information to another
    business or a third party for monetary or other valuable consideration.
      </Text>
      <Text style={styles.mText}>
      Collecting and Using Your Personal Data  
      </Text>
      <Text style={styles.mText}>
      Types of Data Collected  
      </Text>
      <Text style={styles.mText}>
      Personal Data 
      </Text>
      <Text style={styles.mText}>
      While using Our Service, We may ask You to provide Us with certain personally
identifiable information that can be used to contact or identify You.
Personally identifiable information may include, but is not limited to:
      </Text>
      <Text style={styles.mText}>
      Email address
      </Text>
      <Text style={styles.mText}>
      Usage Data
      </Text>
      <Text style={styles.mText}>
      Usage Data  
      </Text>
      <Text style={styles.mText}>
      Usage Data is collected automatically when using the Service.
      </Text>
      <Text style={styles.mText}>
      Usage Data may include information such as Your Device's Internet Protocol
address (e.g. IP address), browser type, browser version, the pages of our
Service that You visit, the time and date of Your visit, the time spent on
those pages, unique device identifiers and other diagnostic data.
      </Text>
      <Text style={styles.mText}>
      When You access the Service by or through a mobile device, We may collect
certain information automatically, including, but not limited to, the type of
mobile device You use, Your mobile device unique ID, the IP address of Your
mobile device, Your mobile operating system, the type of mobile Internet
browser You use, unique device identifiers and other diagnostic data.
      </Text>
      <Text style={styles.mText}>
      We may also collect information that Your browser sends whenever You visit our
Service or when You access the Service by or through a mobile device.
      </Text>
      <Text style={styles.mText}>
      Information Collected while Using the Application 
      </Text>
      <Text style={styles.mText}>
      While using Our Application, in order to provide features of Our Application,
We may collect, with your prior permission:
      </Text>
      <Text style={styles.mText}>
      Information regarding your location
      </Text>
      <Text style={styles.mText}>
      We use this information to provide features of Our Service, to improve and
customize Our Service. The information may be uploaded to the Company's
servers and/or a Service Provider's server or it be simply stored on Your
device.
      </Text>
      <Text style={styles.mText}>
      You can enable or disable access to this information at any time, through Your
Device settings.
      </Text>
      <Text style={styles.mText}>
      Tracking Technologies and Cookies 
      </Text>
      <Text style={styles.mText}>
      We use Cookies and similar tracking technologies to track the activity on Our
Service and store certain information. Tracking technologies used are beacons,
tags, and scripts to collect and track information and to improve and analyze
Our Service.
      </Text>
      <Text style={styles.mText}>
      You can instruct Your browser to refuse all Cookies or to indicate when a
Cookie is being sent. However, if You do not accept Cookies, You may not be
able to use some parts of our Service.
      </Text>
      <Text style={styles.mText}>
      Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on
your personal computer or mobile device when You go offline, while Session
Cookies are deleted as soon as You close your web browser. Learn more about
cookies: [All About Cookies](https://www.termsfeed.com/blog/cookies/).
      </Text>
      <Text style={styles.mText}>
      We use both session and persistent Cookies for the purposes set out below:
      </Text>
      <Text style={styles.mText}>
      Necessary / Essential Cookies
      </Text>
      <Text style={styles.mText}>
      Type: Session Cookies
      </Text>
      <Text style={styles.mText}>
      Administered by: Us
      </Text>
      <Text style={styles.mText}>
      Purpose: These Cookies are essential to provide You with services
    available through the Website and to enable You to use some of its
    features. They help to authenticate users and prevent fraudulent use of
    user accounts. Without these Cookies, the services that You have asked for
    cannot be provided, and We only use these Cookies to provide You with
    those services.
      </Text>
      <Text style={styles.mText}>
      Cookies Policy / Notice Acceptance Cookies
      </Text>
      <Text style={styles.mText}>
      Type: Persistent Cookies
      </Text>
      <Text style={styles.mText}>
      Administered by: Us
      </Text>
      <Text style={styles.mText}>
      Purpose: These Cookies identify if users have accepted the use of cookies
    on the Website.
      </Text>
      <Text style={styles.mText}>
      Functionality Cookies
      </Text>
      <Text style={styles.mText}>
      Type: Persistent Cookies
      </Text>
      <Text style={styles.mText}>
      Administered by: Us
      </Text>
      <Text style={styles.mText}>
      Purpose: These Cookies allow us to remember choices You make when You use
    the Website, such as remembering your login details or language
    preference. The purpose of these Cookies is to provide You with a more
    personal experience and to avoid You having to re-enter your preferences
    every time You use the Website.
      </Text>
      <Text style={styles.mText}>
      Tracking and Performance Cookies
      </Text>
      <Text style={styles.mText}>
      Type: Persistent Cookies
      </Text>
      <Text style={styles.mText}>
      Administered by: Third-Parties
      </Text>
      <Text style={styles.mText}>
      Purpose: These Cookies are used to track information about traffic to the
    Website and how users use the Website. The information gathered via these
    Cookies may directly or indirectly identify you as an individual visitor.
    This is because the information collected is typically linked to a
    pseudonymous identifier associated with the device you use to access the
    Website. We may also use these Cookies to test new advertisements, pages,
    features or new functionality of the Website to see how our users react to
    them.
      </Text>
      <Text style={styles.mText}>
      For more information about the cookies we use and your choices regarding
cookies, please visit our Cookies Policy.
      </Text>
      <Text style={styles.mText}>
      Use of Your Personal Data
      </Text>
      <Text style={styles.mText}>
      The Company may use Personal Data for the following purposes:
      </Text>

      <Text style={styles.text}>
      To provide and maintain our Service, including to monitor the usage of our
    Service.
      </Text>
      <Text style={styles.text}>
      To manage Your Account: to manage Your registration as a user of the
    Service. The Personal Data You provide can give You access to different
    functionalities of the Service that are available to You as a registered
    user
      </Text>
      <Text style={styles.text}>
      For the performance of a contract: the development, compliance and
    undertaking of the purchase contract for the products, items or services
    You have purchased or of any other contract with Us through the Service.
      </Text>
      <Text style={styles.text}>
      To contact You: To contact You by email, telephone calls, SMS, or other
    equivalent forms of electronic communication, such as a mobile
    application's push notifications regarding updates or informative
    communications related to the functionalities, products or contracted
    services, including the security updates, when necessary or reasonable for
    their implementation.
      </Text>
      <Text style={styles.text}>
      To provide You with news, special offers and general information about
    other goods, services and events which we offer that are similar to those
    that you have already purchased or enquired about unless You have opted
    not to receive such information.

      </Text>
      <Text style={styles.mText}>
      To manage Your requests: To attend and manage Your requests to Us.
      </Text>
      <Text style={styles.mText}>
      We may share your personal information in the following situations:
      </Text>
      <Text style={styles.text}>
      With Service Providers: We may share Your personal information with
    Service Providers to monitor and analyze the use of our Service, for
    payment processing, to contact You.
      </Text>
      <Text style={styles.text}>
      For Business transfers: We may share or transfer Your personal information
    in connection with, or during negotiations of, any merger, sale of Company
    assets, financing, or acquisition of all or a portion of our business to
    another company.
      </Text>
      <Text style={styles.text}>
      With Affiliates: We may share Your information with Our affiliates, in
    which case we will require those affiliates to honor this Privacy Policy.
    Affiliates include Our parent company and any other subsidiaries, joint
    venture partners or other companies that We control or that are under
    common control with Us.
      </Text>
      <Text style={styles.text}>
      With Business partners: We may share Your information with Our business
    partners to offer You certain products, services or promotions.
      </Text>
      <Text style={styles.mText}>
      With other users: when You share personal information or otherwise
    interact in the public areas with other users, such information may be
    viewed by all users and may be publicly distributed outside. If You
    interact with other users or register through a Third-Party Social Media
    Service, Your contacts on the Third-Party Social Media Service may see
    Your name, profile, pictures and description of Your activity. Similarly,
    other users will be able to view descriptions of Your activity,
    communicate with You and view Your profile.
      </Text>
      
      <Text style={styles.mText}>
      Retention of Your Personal Data 
      </Text>
      <Text style={styles.mText}>
      The Company will retain Your Personal Data only for as long as is necessary
for the purposes set out in this Privacy Policy. We will retain and use Your
Personal Data to the extent necessary to comply with our legal obligations
(for example, if we are required to retain your data to comply with applicable
laws), resolve disputes, and enforce our legal agreements and policies.
      </Text>
      <Text style={styles.mText}>
      The Company will also retain Usage Data for internal analysis purposes. Usage
Data is generally retained for a shorter period of time, except when this data
is used to strengthen the security or to improve the functionality of Our
Service, or We are legally obligated to retain this data for longer time
periods.
      </Text>
      <Text style={styles.mText}>
      Transfer of Your Personal Data 
      </Text>
      <Text style={styles.mText}>
      Your information, including Personal Data, is processed at the Company's
operating offices and in any other places where the parties involved in the
processing are located. It means that this information may be transferred to —
and maintained on — computers located outside of Your state, province, country
or other governmental jurisdiction where the data protection laws may differ
than those from Your jurisdiction.
      </Text>
      <Text style={styles.mText}>
      Your consent to this Privacy Policy followed by Your submission of such
information represents Your agreement to that transfer.
      </Text>
      <Text style={styles.mText}>
      The Company will take all steps reasonably necessary to ensure that Your data
is treated securely and in accordance with this Privacy Policy and no transfer
of Your Personal Data will take place to an organization or a country unless
there are adequate controls in place including the security of Your data and
other personal information.
      </Text>
      <Text style={styles.mText}>
      Disclosure of Your Personal Data  
      </Text>
      <Text style={styles.mText}>
      Business Transactions 
      </Text>
      <Text style={styles.mText}>
      If the Company is involved in a merger, acquisition or asset sale, Your
Personal Data may be transferred. We will provide notice before Your Personal
Data is transferred and becomes subject to a different Privacy Policy.
      </Text>
      <Text style={styles.mText}>
      Law enforcement 
      </Text>
      <Text style={styles.mText}>
      Under certain circumstances, the Company may be required to disclose Your
Personal Data if required to do so by law or in response to valid requests by
public authorities (e.g. a court or a government agency).
      </Text>
      <Text style={styles.mText}>
      Other legal requirements  
      </Text>
      <Text style={styles.mText}>
      The Company may disclose Your Personal Data in the good faith belief that such
action is necessary to:
      </Text>
      <Text style={styles.text}>
      Comply with a legal obligation
      </Text>
      <Text style={styles.text}>
      Protect and defend the rights or property of the Company
      </Text>
      <Text style={styles.text}>
      Prevent or investigate possible wrongdoing in connection with the Service
      </Text>
      <Text style={styles.text}>
      Protect the personal safety of Users of the Service or the public
      </Text>
      <Text style={styles.mText}>
      Protect against legal liability
      </Text>
      <Text style={styles.mText}>
      Security of Your Personal Data  
      </Text>
      <Text style={styles.mText}>
      The security of Your Personal Data is important to Us, but remember that no
method of transmission over the Internet, or method of electronic storage is
100% secure. While We strive to use commercially acceptable means to protect
Your Personal Data, We cannot guarantee its absolute security.
      </Text>
      <Text style={styles.mText}>
      Detailed Information on the Processing of Your Personal Data 
      </Text>
      <Text style={styles.mText}>
      Service Providers have access to Your Personal Data only to perform their
tasks on Our behalf and are obligated not to disclose or use it for any other
purpose.
      </Text>
      <Text style={styles.mText}>
      Analytics 
      </Text>
      <Text style={styles.mText}>
      We may use third-party Service providers to monitor and analyze the use of our
Service.
      </Text>
      <Text style={styles.mText}>
      Google Analytics
      </Text>
      <Text style={styles.mText}>
      Google Analytics is a web analytics service offered by Google that tracks
    and reports website traffic. Google uses the data collected to track and
    monitor the use of our Service. This data is shared with other Google
    services. Google may use the collected data to contextualise and
    personalise the ads of its own advertising network.
      </Text>
      <Text style={styles.mText}>
      For more information on the privacy practices of Google, please visit the
    Google Privacy Terms web page:
    https://policies.google.com/privacy?hl=en
      </Text>
      <Text style={styles.mText}>
      Mixpanel
      </Text>
      <Text style={styles.mText}>
      Mixpanel is provided by Mixpanel Inc.
      </Text>
      <Text style={styles.mText}>
      You can prevent Mixpanel from using your information for analytics
    purposes by opting-out. To opt-out of Mixpanel service, please visit this
    page: https://mixpanel.com/optout
      </Text>
      <Text style={styles.mText}>
      For more information on what type of information Mixpanel collects, please
    visit the Terms of Use page of Mixpanel: https://mixpanel.com/terms
      </Text>
      <Text style={styles.mText}>
      Email Marketing  
      </Text>
      <Text style={styles.mText}>
      We may use Your Personal Data to contact You with newsletters, marketing or
promotional materials and other information that may be of interest to You.
You may opt-out of receiving any, or all, of these communications from Us by
following the unsubscribe link or instructions provided in any email We send
or by contacting Us.
      </Text>
      <Text style={styles.mText}>
      We may use Email Marketing Service Providers to manage and send emails to You.
      </Text>
      <Text style={styles.mText}>
      Mailchimp
      </Text>
      <Text style={styles.mText}>
      Mailchimp is an email marketing sending service provided by The Rocket
    Science Group LLC.
      </Text>
      <Text style={styles.mText}>
      For more information on the privacy practices of Mailchimp, please visit
    their Privacy policy: https://mailchimp.com/legal/privacy
      </Text>
      <Text style={styles.mText}>
      Payments
      </Text>
      <Text style={styles.mText}>
      We may provide paid products and/or services within the Service. In that case,
we may use third-party services for payment processing (e.g. payment
processors).
      </Text>
      <Text style={styles.mText}>
      We will not store or collect Your payment card details. That information is
provided directly to Our third-party payment processors whose use of Your
personal information is governed by their Privacy Policy. These payment
processors adhere to the standards set by PCI-DSS as managed by the PCI
Security Standards Council, which is a joint effort of brands like Visa,
Mastercard, American Express and Discover. PCI-DSS requirements help ensure
the secure handling of payment information.
      </Text>
      <Text style={styles.mText}>
      Their Privacy Policy can be viewed at https://stripe.com/us/privacy
      </Text>
      <Text style={styles.mText}>
      CCPA Privacy 
      </Text>
      <Text style={styles.mText}>
      Your Rights under the CCPA  
      </Text>
      <Text style={styles.mText}>
      Under this Privacy Policy, and by law if You are a resident of California, You
have the following rights:
      </Text>
      <Text style={styles.text}>
      The right to notice. You must be properly notified which categories of
    Personal Data are being collected and the purposes for which the Personal
    Data is being used.
      </Text>
      <Text style={styles.text}>
      The right to access / the right to request. The CCPA permits You to
    request and obtain from the Company information regarding the disclosure
    of Your Personal Data that has been collected in the past 12 months by the
    Company or its subsidiaries to a third-party for the third party's direct
    marketing purposes.
      </Text>
      <Text style={styles.text}>
      The right to say no to the sale of Personal Data. You also have the right
    to ask the Company not to sell Your Personal Data to third parties. You
    can submit such a request by visiting our "Do Not Sell My Personal
    Information" section or web page.
      </Text>
      <Text style={styles.mText}>
      The right to know about Your Personal Data. You have the right to request
    and obtain from the Company information regarding the disclosure of the
    following:
      </Text>
      <Text style={styles.text}>
      The categories of Personal Data collected
      </Text>
      <Text style={styles.text}>
      The sources from which the Personal Data was collected
      </Text>
      <Text style={styles.text}>
      The business or commercial purpose for collecting or selling the
      Personal Data
      </Text>
      <Text style={styles.text}>
      Categories of third parties with whom We share Personal Data
      </Text>
      <Text style={styles.text}>
      The specific pieces of Personal Data we collected about You
      </Text>
      <Text style={styles.text}>
      The right to delete Personal Data. You also have the right to request the
    deletion of Your Personal Data that have been collected in the past 12
    months.
      </Text>
      <Text style={styles.text}>
      The right not to be discriminated against. You have the right not to be
    discriminated against for exercising any of Your Consumer's rights,
    including by:
      </Text>
      <Text style={styles.text}>
      Denying goods or services to You
      </Text>
      <Text style={styles.text}>
      Charging different prices or rates for goods or services, including the
      use of discounts or other benefits or imposing penalties
      </Text>
      <Text style={styles.text}>
      Providing a different level or quality of goods or services to You
      </Text>
      <Text style={styles.mText}>
      Suggesting that You will receive a different price or rate for goods or
      services or a different level or quality of goods or services.
      </Text>
      <Text style={[styles.mText, { marginBottom: 70 }]}>
      Exercising Your CCPA Data Protection Rights
      </Text>
      <Text style={styles.mText}>
      In order to exercise any of Your rights under the CCPA, and if you are a
California resident, You can email or call us or visit our "Do Not Sell My
Personal Information" section or web page.
      </Text>
      <Text style={styles.mText}>
      The Company will disclose and deliver the required information free of charge
within 45 days of receiving Your verifiable request. The time period to
provide the required information may be extended once by an additional 45 days
when reasonable necessary and with prior notice.
      </Text>
      <Text style={styles.mText}>
      Do Not Sell My Personal Information
      </Text>
      <Text style={styles.mText}>
      We do not sell personal information. However, the Service Providers we partner
with (for example, our advertising partners) may use technology on the Service
that "sells" personal information as defined by the CCPA law.
      </Text>
      <Text style={styles.mText}>
      If you wish to opt out of the use of your personal information for interest-
based advertising purposes and these potential sales as defined under CCPA
law, you may do so by following the instructions below.
      </Text>
      <Text style={styles.mText}>
      Please note that any opt out is specific to the browser You use. You may need
to opt out on every browser that you use.
      </Text>
      <Text style={styles.mText}>
      Website  
      </Text>
      <Text style={styles.mText}>
      You can opt out of receiving ads that are personalized as served by our
Service Providers by following our instructions presented on the Service:
      </Text>
      <Text style={styles.text}>
      From Our "Cookie Consent" notice banner
      </Text>
      <Text style={styles.text}>
      Or from Our "CCPA Opt-out" notice banner
      </Text>
      <Text style={styles.text}>
      Or from Our "Do Not Sell My Personal Information" notice banner
      </Text>
      <Text style={styles.text}>
      Or from Our "Do Not Sell My Personal Information" link
      </Text>
      <Text style={styles.mText}>
      The opt out will place a cookie on Your computer that is unique to the browser
You use to opt out. If you change browsers or delete the cookies saved by your
browser, you will need to opt out again.
      </Text>
      <Text style={styles.mText}>
      Mobile Devices
      </Text>
      <Text style={styles.mText}>
      Your mobile device may give you the ability to opt out of the use of
information about the apps you use in order to serve you ads that are targeted
to your interests:
      </Text>
      <Text style={styles.mText}>
      "Opt out of Interest-Based Ads" or "Opt out of Ads Personalization" on
    Android devices
      </Text>
      <Text style={styles.mText}>
      "Limit Ad Tracking" on iOS devices
      </Text>
      <Text style={styles.mText}>
      You can also stop the collection of location information from Your mobile
device by changing the preferences on your mobile device.
      </Text>
      <Text style={styles.mText}>
      "Do Not Track" Policy as Required by California Online Privacy Protection Act
(CalOPPA) 
      </Text>
      <Text style={styles.mText}>
      Our Service does not respond to Do Not Track signals.
      </Text>
      <Text style={styles.mText}>
      However, some third party websites do keep track of Your browsing activities.
If You are visiting such websites, You can set Your preferences in Your web
browser to inform websites that You do not want to be tracked. You can enable
or disable DNT by visiting the preferences or settings page of Your web
browser.
      </Text>
      <Text style={styles.mText}>
      Children's Privacy 
      </Text>
      <Text style={styles.mText}>
      Our Service does not address anyone under the age of 13. We do not knowingly
collect personally identifiable information from anyone under the age of 13.
If You are a parent or guardian and You are aware that Your child has provided
Us with Personal Data, please contact Us. If We become aware that We have
collected Personal Data from anyone under the age of 13 without verification
of parental consent, We take steps to remove that information from Our
servers.
      </Text>
      <Text style={styles.mText}>
      If We need to rely on consent as a legal basis for processing Your information
and Your country requires consent from a parent, We may require Your parent's
consent before We collect and use that information.
      </Text>
      <Text style={styles.mText}>
      Your California Privacy Rights (California's Shine the Light law) 
      </Text>
      <Text style={styles.mText}>
      Under California Civil Code Section 1798 (California's Shine the Light law),
California residents with an established business relationship with us can
request information once a year about sharing their Personal Data with third
parties for the third parties' direct marketing purposes.
      </Text>
      <Text style={styles.mText}>
      If you'd like to request more information under the California Shine the Light
law, and if you are a California resident, You can contact Us using the
contact information provided below.
      </Text>
      <Text style={styles.mText}>
      California Privacy Rights for Minor Users (California Business and Professions
Code Section 22581) 
      </Text>
      <Text style={styles.mText}>
      California Business and Professions Code section 22581 allow California
residents under the age of 18 who are registered users of online sites,
services or applications to request and obtain removal of content or
information they have publicly posted.
      </Text>
      <Text style={styles.mText}>
      To request removal of such data, and if you are a California resident, You can
contact Us using the contact information provided below, and include the email
address associated with Your account.
      </Text>
      <Text style={styles.mText}>
      Be aware that Your request does not guarantee complete or comprehensive
removal of content or information posted online and that the law may not
permit or require removal in certain circumstances.
      </Text>
      <Text style={styles.mText}>
      Links to Other Websites  
      </Text>
      <Text style={styles.mText}>
      Our Service may contain links to other websites that are not operated by Us.
If You click on a third party link, You will be directed to that third party's
site. We strongly advise You to review the Privacy Policy of every site You
visit.
      </Text>
      <Text style={styles.mText}>
      We have no control over and assume no responsibility for the content, privacy
policies or practices of any third party sites or services.
      </Text>
      <Text style={styles.mText}>
      Changes to this Privacy Policy
      </Text>
      <Text style={styles.mText}>
      We may update our Privacy Policy from time to time. We will notify You of any
changes by posting the new Privacy Policy on this page.
      </Text>
      <Text style={styles.mText}>
      We will let You know via email and/or a prominent notice on Our Service, prior
to the change becoming effective and update the "Last updated" date at the top
of this Privacy Policy.
      </Text>
      <Text style={styles.mText}>
      You are advised to review this Privacy Policy periodically for any changes.
Changes to this Privacy Policy are effective when they are posted on this
page.
      </Text>
      <Text style={styles.mText}>
      Contact Us 
      </Text>
      <Text style={styles.mText}>
      If you have any questions about this Privacy Policy, You can contact us:
      </Text>
      <Text style={styles.mText}>
      By email: admin@paradyse.app
      </Text>
      <Text style={styles.mText}>
      By phone number: ‪2014557720‬
      </Text>
    </ScrollView>
  );
};

export default PrivacyPolicyView;
